In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:

df = pd.read_csv('movies_metadata.csv')

In [3]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16862 entries, 0 to 16861
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  16862 non-null  bool
 1   belongs_to_collection  2109 non-null   object
 2   budget                 16862 non-null  int64
 3   genres                 16862 non-null  object
 4   homepage               2241 non-null   object
 5   id                     16862 non-null  int64
 6   imdb_id                16859 non-null  object
 7   original_language      16862 non-null  object
 8   original_title         16862 non-null  object
 9   overview               16783 non-null  object
 10  popularity             16862 non-null  float64
 11  poster_path            16810 non-null  object
 12  production_companies   16861 non-null  object
 13  production_countries   16861 non-null  object
 14  release_date           16853 non-null  object
 15  revenue                16861 non-null  float64
 16  runtime                16846 non-null  float64
 17  spoken_languages       16861 non-null  object
 18  status                 16848 non-null  object
 19  tagline                10383 non-null  object
 20  title                  16861 non-null  object
 21  video                  16861 non-null  object
 22  vote_average           16861 non-null  float64
 23  vote_count             16861 non-null  float64
dtypes: bool(1), float64(5), int64(2), object(16)
memory usage: 3.0+ MB

In [6]:
print (df.shape)
df.isnull().sum()

(16862, 24)

adult                        0
belongs_to_collection    14753
budget                       0
genres                       0
homepage                 14621
id                           0
imdb_id                      3
original_language            0
original_title               0
overview                    79
popularity                   0
poster_path                 52
production_companies         1
production_countries         1
release_date                 9
revenue                      1
runtime                     16
spoken_languages             1
status                      14
tagline                   6479
title                        1
video                        1
vote_average                 1
vote_count                   1
dtype: int64

In [7]:
df = df.drop_duplicates().reset_index(drop = True)

In [8]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16852,False,NaN,6000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.panegre.com/,57521,tt1454523,ca,Pa Negre,In the harsh post-war years' Catalan countrysi...,...,2010-10-10,3770657.0,108.0,"[{'iso_639_1': 'ca', 'name': 'Català'}, {'iso_...",Released,The lies of adults raise little monsters.,Black Bread,False,6.9,33.0
16853,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,13847,tt0019630,en,Alibi,"Chick Williams, a prohibition gangster, rejoin...",...,1929-04-20,0.0,91.0,[],Released,NaN,Alibi,False,3.3,4.0
16854,False,NaN,0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",NaN,24926,tt0170811,en,Winnie the Pooh and a Day for Eeyore,Winnie the Pooh and friends decide to throw a ...,...,1983-01-01,12000000.0,25.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Winnie the Pooh and a Day for Eeyore,False,5.9,9.0
16855,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,10356,tt0372303,en,The Good Shepherd,CHRISTIAN SLATER plays a worldly and urbane pr...,...,2004-03-21,0.0,88.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Good Shepherd,False,4.3,6.0
16856,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,37405,tt0765444,de,Eden,Fat German star restaurant chef Gregor shows r...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.isnull().sum()

adult                        0
belongs_to_collection    14748
budget                       0
genres                       0
homepage                 14616
id                           0
imdb_id                      3
original_language            0
original_title               0
overview                    79
popularity                   0
poster_path                 52
production_companies         1
production_countries         1
release_date                 9
revenue                      1
runtime                     16
spoken_languages             1
status                      14
tagline                   6478
title                        1
video                        1
vote_average                 1
vote_count                   1
dtype: int64

In [10]:
df = df.dropna(subset=['title'])

In [11]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16851,False,NaN,0,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thenewdaughter.com/,37534,tt0951335,en,The New Daughter,John James is a writer; his wife has left him....,...,2009-12-18,0.0,108.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,How Far Will A Father Go To Protect The Ones H...,The New Daughter,False,5.2,109.0
16852,False,NaN,6000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.panegre.com/,57521,tt1454523,ca,Pa Negre,In the harsh post-war years' Catalan countrysi...,...,2010-10-10,3770657.0,108.0,"[{'iso_639_1': 'ca', 'name': 'Català'}, {'iso_...",Released,The lies of adults raise little monsters.,Black Bread,False,6.9,33.0
16853,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,13847,tt0019630,en,Alibi,"Chick Williams, a prohibition gangster, rejoin...",...,1929-04-20,0.0,91.0,[],Released,NaN,Alibi,False,3.3,4.0
16854,False,NaN,0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",NaN,24926,tt0170811,en,Winnie the Pooh and a Day for Eeyore,Winnie the Pooh and friends decide to throw a ...,...,1983-01-01,12000000.0,25.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Winnie the Pooh and a Day for Eeyore,False,5.9,9.0
16855,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,10356,tt0372303,en,The Good Shepherd,CHRISTIAN SLATER plays a worldly and urbane pr...,...,2004-03-21,0.0,88.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Good Shepherd,False,4.3,6.0

In [12]:
df['overview'] = df['overview'].fillna('')

In [13]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [14]:
import ast
df['genres'] = df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

In [15]:
df['tagline'] = df['tagline'].fillna('')

In [16]:
df.isnull().sum()

adult                        0
belongs_to_collection    14747
budget                       0
genres                       0
homepage                 14615
id                           0
imdb_id                      3
original_language            0
original_title               0
overview                     0
popularity                   0
poster_path                 52
production_companies         0
production_countries         0
release_date                 8
revenue                      0
runtime                     15
spoken_languages             0
status                      13
tagline                      0
title                        0
video                        0
vote_average                 0
vote_count                   0
dtype: int64

In [17]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,Animation Comedy Family,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,Adventure Fantasy Family,NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,Romance Comedy,NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,Comedy Drama Romance,NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,Comedy,NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [19]:
df['tags'] = df['overview']+ " " + df['genres'] +" "+ df['tagline']

In [20]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [21]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [22]:

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [23]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [24]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #removed the punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [25]:
df['tags'] = df['tags'].apply(preprocess_text)

In [26]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Toy Story                                   0
Jumanji                                     1
Grumpier Old Men                            2
Waiting to Exhale                           3
Father of the Bride Part II                 4
                                        ...
The New Daughter                        16851
Black Bread                             16852
Alibi                                   16853
Winnie the Pooh and a Day for Eeyore    16854
The Good Shepherd                       16855
Length: 16856, dtype: int64

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [29]:

tfidf_matrix = tfidf.fit_transform(df['tags'])

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

In [31]:

def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [40]:
recommend('Toy Story')

2996                Toy Story 2
15344               Toy Story 3
6434     What's Up, Tiger Lily?
11396    For Your Consideration
1071      Rebel Without a Cause
485                      Malice
1931                  Condorman
7253             Africa Screams
10937                  The Wild
1032              The Sunchaser
Name: title, dtype: object

In [37]:

import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))